### ISSUE TITLE
No output at all in powershell tab of windows terminal

### ISSUE THREAD

**Issue by shengxue** [banga/git-split-diffs#13]
When I ran ```git diff | git-split-diffs --color | less``` in powershell tab of windows terminal,  there is nothing in the output.

**Comment by banga** [comment]
Sorry I'm not too familiar with powershell – is `less` available there? It seems that maybe `more` is what you need? https://4sysops.com/archives/displaying-text-one-page-at-a-time-in-powershell-more-less-head-tail/

**Comment by shengxue** [comment]
Neither ```more``` nor ```less``` works. :(

```git diff | git-split-diffs --color``` has no output either.

**Comment by banga** [comment]
Hmm strange. Does the command exit? Do you have anything special in your git config? If it’s safe to share, can you share the output of git diff and git config -l?

**Comment by shengxue** [comment]
The command does not exit.

you are right that I have git configure on diff:
```
diff.tool=vscode
difftool.vscode.cmd=code --wait --diff $LOCAL $REMOTE
merge.tool=vscode
mergetool.vscode.cmd=code --wait $MERGED
```

**Comment by banga** [comment]
Oh ok. `git-split-diffs` reads from the output of git commands, so it's not working for `git diff` for you since you're making it open vscode instead. It doesn't exist because you probably have the diff open in vscode and it's waiting for vscode to close the diff. If you want to use this for other git commands, I'd recommend setting the `core.pager` setting mentioned in the README. That way, other commands like `git log -p` and `git show` will show you diffs with `git-split-diffs` but git diff will open up vscode. Or, you can remove the above settings and use `git-split-diffs` manually like in your original post.

**Comment by shengxue** [comment]
@banga   it is quite weird that a simple ```git diff``` gives perfect output

**Comment by banga** [comment]
hmm so `git diff` doesn't open vscode for you?

**Comment by pchren** [comment]
Hi, any idea how to make it work with some less equivalent in powershell?
